name: Audit dependencies

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 1'
  push:
      branches: ["main"]
  pull_request:
      branches: ["main"]

jobs:
  audit_deps:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7.0.1

      - uses: EmbarkStudios/cargo-deny-action@v2
        with:
          command: check
