name: Generate changelog

on:
    push:
        branches: ["main"]

jobs:
    changelog:
        name: Generate changelog
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                fetch-depth: 0

            - name: Generate a changelog
              uses: orhun/git-cliff-action@v4
              id: git-cliff
              with:
                  config: cliff.toml
                  args: --verbose
              env:
                  OUTPUT: CHANGELOG.md

            - name: Commit changes
              run: |
                git checkout main
                git config user.name 'github-actions[bot]'
                git config user.email 'github-actions[bot]@users.noreply.github.com'
                set +e
                git add CHANGELOG.md
                git commit -m "[skip ci] Update CHANGELOG.md"
                git push https://${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git main

