name: Test

on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]

env:
    CARGO_TERM_COLOR: always

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3

            - name: Install stable toolchain
              run: rustup toolchain install stable

            - name: Install libpango
              run: sudo apt-get install libpango1.0-dev

            - name: Cache dependencies
              uses: Swatinem/rust-cache@v2

            - name: Check
              run: cargo check

            - name: Build
              run: cargo build

            - name: Format
              run: cargo fmt --check

            - name: Lint
              run: cargo clippy -- -D warnings
